import argparse
import importlib
import sys
import time
from datetime import datetime
from pathlib import Path

import MetaTrader5 as mt5
import pandas as pd

from execution_rules import MAX_TRADES_PER_DAY, START_BALANCE, TP_R, build_trade_plan


BASE_DIR = Path(__file__).resolve().parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from config import PAIR as DEFAULT_PAIR
from config import STRATEGY as DEFAULT_STRATEGY

try:
    from config import ENTRY_TIMEFRAME as DEFAULT_ENTRY_TIMEFRAME
except ImportError:
    DEFAULT_ENTRY_TIMEFRAME = "M15"

try:
    from config import TREND_TIMEFRAME as DEFAULT_TREND_TIMEFRAME
except ImportError:
    DEFAULT_TREND_TIMEFRAME = "M30"


AVAILABLE_STRATEGIES = {
    "step_trend": "strategy_step_trend",
    "volume": "strategy_volume",
    "step_pro": "strategy_step_pro",
    "scalper": "strategy_scalper",
    "sniper_v4": "strategy_sniper_v4",
    "sniper_v4_1": "strategy_sniper_v4_1",
    "legacy": "strategy",
}

TIMEFRAME_MAP = {
    "M1": mt5.TIMEFRAME_M1,
    "M5": mt5.TIMEFRAME_M5,
    "M15": mt5.TIMEFRAME_M15,
    "M30": mt5.TIMEFRAME_M30,
    "H1": mt5.TIMEFRAME_H1,
}

DEFAULT_MAX_SIGNALS_PER_DAY = MAX_TRADES_PER_DAY


try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except AttributeError:
    pass


def load_strategy(strategy_name):
    module_name = AVAILABLE_STRATEGIES.get(strategy_name)
    if not module_name:
        available = ", ".join(sorted(AVAILABLE_STRATEGIES))
        raise ValueError(
            f"Unsupported strategy '{strategy_name}'. Available strategies: {available}"
        )

    return importlib.import_module(module_name)


def connect():
    if mt5.initialize():
        print("Connected to MT5")
        return True

    print(f"Failed to connect to MT5. Error: {mt5.last_error()}")
    return False


def fetch_data(symbol, timeframe, bars=500):
    mt5_timeframe = TIMEFRAME_MAP.get(timeframe)
    if mt5_timeframe is None:
        valid = ", ".join(TIMEFRAME_MAP)
        raise ValueError(f"Invalid timeframe '{timeframe}'. Valid values: {valid}")

    rates = mt5.copy_rates_from_pos(symbol, mt5_timeframe, 0, bars)
    if rates is None or len(rates) == 0:
        print(f"No data received for {symbol} on {timeframe}")
        return None

    df = pd.DataFrame(rates)
    df.columns = [
        "time",
        "open",
        "high",
        "low",
        "close",
        "tick_volume",
        "spread",
        "real_volume",
    ]
    df["time"] = pd.to_datetime(df["time"], unit="s")
    return df


def analyze_timeframe(module, pair, timeframe, bars):
    raw_df = fetch_data(pair, timeframe, bars=bars)
    if raw_df is None or len(raw_df) < 3:
        return None

    closed_df = raw_df.iloc[:-1].copy()
    analyzed_df = module.calculate_indicators(closed_df)

    if hasattr(module, "analyze_setup"):
        analysis = module.analyze_setup(analyzed_df)
    else:
        signal = module.generate_signal(analyzed_df)
        analysis = {
            "signal": signal,
            "reason": "Signal generated by strategy module.",
            "checks": {},
        }

    latest_closed_candle = analyzed_df.iloc[-1][["time", "open", "high", "low", "close"]]
    analysis["latest_closed_candle"] = latest_closed_candle
    analysis["next_open_candle"] = raw_df.iloc[-1][["time", "open", "high", "low", "close"]]
    analysis["timeframe"] = timeframe
    return analysis


def format_check(name, value):
    if isinstance(value, bool):
        return f"  - {name}: {'PASS' if value else 'FAIL'}"
    return f"  - {name}: {value}"


def determine_higher_timeframe_bias(trend_analysis):
    checks = trend_analysis.get("checks", {})
    trend_bias = checks.get("trend_bias", "NEUTRAL")
    market_choppy = checks.get("market_choppy", True)
    timeframe = trend_analysis.get("timeframe", "higher timeframe")

    if trend_bias == "STRONG_BUY":
        return "BUY", "strong", f"{timeframe} strong bullish bias: EMA stack and 200 EMA slope agree."
    if trend_bias == "STRONG_SELL":
        return "SELL", "strong", f"{timeframe} strong bearish bias: EMA stack and 200 EMA slope agree."
    if trend_bias == "WEAK_BUY":
        return "BUY", "weak", f"{timeframe} weak bullish bias: price is still supported above the 200 EMA."
    if trend_bias == "WEAK_SELL":
        return "SELL", "weak", f"{timeframe} weak bearish bias: price is still contained below the 200 EMA."
    if market_choppy:
        return "NEUTRAL", "neutral", f"{timeframe} trend is choppy, so no entry bias is allowed."
    return "NEUTRAL", "neutral", f"{timeframe} trend is unclear."


def combine_analyses(trend_analysis, entry_analysis):
    higher_bias, bias_strength, bias_reason = determine_higher_timeframe_bias(trend_analysis)
    entry_signal = entry_analysis["signal"]
    entry_reason = entry_analysis["reason"]

    if higher_bias == "NEUTRAL":
        final_signal = "WAIT"
        final_reason = f"No trade: {bias_reason}"
    elif entry_signal == "WAIT":
        final_signal = "WAIT"
        final_reason = (
            f"No trade: higher timeframe {bias_strength} bias agrees to look for {higher_bias}, "
            f"but entry timeframe says WAIT. {entry_reason}"
        )
    elif entry_signal != higher_bias:
        final_signal = "WAIT"
        final_reason = (
            f"No trade: entry timeframe shows {entry_signal}, but it conflicts with the higher timeframe {higher_bias} bias."
        )
    else:
        final_signal = entry_signal
        final_reason = (
            f"{entry_signal} setup confirmed: higher timeframe bias and entry timeframe signal align."
        )

    return {
        "signal": final_signal,
        "reason": final_reason,
        "higher_bias": higher_bias,
        "bias_strength": bias_strength,
        "bias_reason": bias_reason,
    }


def print_analysis(result, pair, strategy_name, max_signals, signals_today):
    trend = result["trend_analysis"]
    entry = result["entry_analysis"]
    trend_candle = trend["latest_closed_candle"]
    entry_candle = entry["latest_closed_candle"]

    print("=" * 72)
    print(
        f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] "
        f"{pair} | strategy={strategy_name}"
    )
    print(
        f"{trend['timeframe']} trend candle: {trend_candle['time']} | "
        f"O={trend_candle['open']} H={trend_candle['high']} "
        f"L={trend_candle['low']} C={trend_candle['close']}"
    )
    print(
        f"{entry['timeframe']} entry candle: {entry_candle['time']} | "
        f"O={entry_candle['open']} H={entry_candle['high']} "
        f"L={entry_candle['low']} C={entry_candle['close']}"
    )
    print(
        f"Projected execution candle: {entry['next_open_candle']['time']} | "
        f"open={entry['next_open_candle']['open']}"
    )
    print(
        f"{trend['timeframe']} bias: {result['higher_bias']} ({result['bias_strength']}) | "
        f"{result['bias_reason']}"
    )
    print(f"Final signal: {result['signal']} | Reason: {result['reason']}")
    if result.get("trade_plan"):
        plan = result["trade_plan"]
        print(
            f"Official trade plan: entry={plan['entry']:.2f} | sl={plan['sl']:.2f} | "
            f"tp={plan['tp']:.2f} | atr={plan['atr']:.2f} | size={plan['size']:.4f} | "
            f"risk={plan['risk_amount']:.2f}"
        )
    print(f"Daily signals used: {signals_today}/{max_signals}")
    print(f"{trend['timeframe']} checks:")
    for key in [
        "trend_up",
        "trend_down",
        "weak_trend_up",
        "weak_trend_down",
        "trend_bias",
        "market_choppy",
        "price_above_200",
        "price_below_200",
        "ema_stack_bullish",
        "ema_stack_bearish",
        "ema_fast",
        "ema",
        "ema_long",
        "ema_fast_slope",
        "ema_slope",
        "ema_long_slope",
        "rsi",
        "rsi_slope",
        "atr",
        "atr_ratio",
    ]:
        if key in trend.get("checks", {}):
            print(format_check(key, trend["checks"][key]))

    print(f"{entry['timeframe']} checks:")
    for key in [
        "trend_up",
        "trend_down",
        "weak_trend_up",
        "weak_trend_down",
        "trend_bias",
        "market_choppy",
        "valid_pullback_buy",
        "valid_pullback_sell",
        "bullish_candle",
        "bearish_candle",
        "engulfing",
        "bullish_continuation",
        "bearish_continuation",
        "bullish_pinbar",
        "bearish_pinbar",
        "bullish_confirmation",
        "bearish_confirmation",
        "confirmation_type",
        "broke_high",
        "broke_low",
        "bullish_breakout_ok",
        "bearish_breakout_ok",
        "strong_confirmation",
        "momentum_up",
        "momentum_down",
        "ema_fast",
        "ema",
        "ema_long",
        "ema_fast_slope",
        "ema_slope",
        "ema_long_slope",
        "rsi",
        "rsi_slope",
        "atr",
        "atr_ratio",
        "recent_high",
        "recent_low",
        "body_ratio",
        "close_position",
        "upper_wick_ratio",
        "lower_wick_ratio",
    ]:
        if key in entry.get("checks", {}):
            print(format_check(key, entry["checks"][key]))


def run_once(
    module,
    strategy_name,
    pair,
    trend_timeframe,
    entry_timeframe,
    bars,
    session_state,
    max_signals_per_day,
):
    trend_analysis = analyze_timeframe(module, pair, trend_timeframe, bars)
    entry_analysis = analyze_timeframe(module, pair, entry_timeframe, bars)

    if trend_analysis is None or entry_analysis is None:
        print("Unable to fetch market data.")
        return False

    combined = combine_analyses(trend_analysis, entry_analysis)
    combined["trend_analysis"] = trend_analysis
    combined["entry_analysis"] = entry_analysis
    combined["trade_plan"] = None

    if combined["signal"] in {"BUY", "SELL"}:
        atr = entry_analysis.get("checks", {}).get("atr")
        projected_entry = entry_analysis["next_open_candle"]["open"]
        if atr:
            combined["trade_plan"] = build_trade_plan(
                combined["signal"],
                projected_entry,
                float(atr),
                START_BALANCE,
                tp_r=TP_R,
            )

    entry_candle_time = entry_analysis["latest_closed_candle"]["time"]
    session_date = datetime.now().date().isoformat()
    if session_state["date"] != session_date:
        session_state["date"] = session_date
        session_state["signals_today"] = 0
        session_state["last_entry_candle"] = None

    if session_state["last_entry_candle"] == entry_candle_time:
        return True

    if (
        session_state["signals_today"] >= max_signals_per_day
        and combined["signal"] in {"BUY", "SELL"}
    ):
        combined["reason"] = (
            f"Signal blocked: daily trade limit of {max_signals_per_day} reached. "
            f"Original setup was {combined['signal']}."
        )
        combined["signal"] = "WAIT"

    if combined["signal"] in {"BUY", "SELL"}:
        session_state["signals_today"] += 1

    session_state["last_entry_candle"] = entry_candle_time
    print_analysis(
        combined,
        pair,
        strategy_name,
        max_signals_per_day,
        session_state["signals_today"],
    )
    return True


def parse_args():
    parser = argparse.ArgumentParser(description="Run the Deriv trading bot.")
    parser.add_argument(
        "--strategy",
        default=DEFAULT_STRATEGY,
        help=f"Strategy name. Default: {DEFAULT_STRATEGY}",
    )
    parser.add_argument(
        "--pair",
        default=DEFAULT_PAIR,
        help=f"Market symbol. Default: {DEFAULT_PAIR}",
    )
    parser.add_argument(
        "--trend-timeframe",
        default=DEFAULT_TREND_TIMEFRAME,
        help=f"Higher timeframe for market bias. Default: {DEFAULT_TREND_TIMEFRAME}",
    )
    parser.add_argument(
        "--entry-timeframe",
        default=DEFAULT_ENTRY_TIMEFRAME,
        help=f"Lower timeframe for entries. Default: {DEFAULT_ENTRY_TIMEFRAME}",
    )
    parser.add_argument(
        "--bars",
        type=int,
        default=500,
        help="Number of candles to fetch. Default: 500",
    )
    parser.add_argument(
        "--watch",
        action="store_true",
        help="Keep polling for new signals instead of running once.",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=60,
        help="Polling interval in seconds when using --watch. Default: 60",
    )
    parser.add_argument(
        "--max-signals",
        type=int,
        default=DEFAULT_MAX_SIGNALS_PER_DAY,
        help="Maximum BUY/SELL signals allowed per day. Default: 3",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    module = load_strategy(args.strategy)
    session_state = {"date": None, "signals_today": 0, "last_entry_candle": None}

    print("Starting Trading Bot...")
    print(
        f"Rule card mode: {args.trend_timeframe} trend bias + "
        f"{args.entry_timeframe} pullback and confirmation entry"
    )

    if not connect():
        return

    try:
        if args.watch:
            print(
                f"Watching {args.pair} | trend={args.trend_timeframe} | "
                f"entry={args.entry_timeframe} | every {args.interval}s | "
                f"max daily signals: {args.max_signals}"
            )
            while True:
                run_once(
                    module,
                    args.strategy,
                    args.pair,
                    args.trend_timeframe,
                    args.entry_timeframe,
                    args.bars,
                    session_state,
                    args.max_signals,
                )
                time.sleep(args.interval)
        else:
            run_once(
                module,
                args.strategy,
                args.pair,
                args.trend_timeframe,
                args.entry_timeframe,
                args.bars,
                session_state,
                args.max_signals,
            )
    finally:
        mt5.shutdown()
        print("MT5 connection closed.")


if __name__ == "__main__":
    main()
